[package]
name = "moteus"
version = "0.3.1"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/omelia-iliffe/moteus-rs"
description = "Rust library for interfacing with Moteus controllers"

[dependencies]
fdcanusb = { version = "0.6.3", optional = true, default-features = false, features = [
    "serial2",
] }
hex = "0.4.3"
byteorder = "1.5.0"
zerocopy = { version = "0.8.25", features = ["derive"] }
num-traits = "0.2.18"
num-derive = "0.4.2"
log = "0.4.21"
itertools = "0.14.0"
env_logger = "0.11.3"
chrono = "0.4.35"
thiserror = "2"

[features]
default = []
fdcanusb = []
log = ["fdcanusb/log"]
aux_index_raw = []

[lib]
doctest = false

[[example]]
name = "simple"
required-features = ["fdcanusb"]

[[example]]
name = "trajectory_test"
required-features = ["fdcanusb"]
